In [1]:
import numpy as np

In [10]:
a = np.array([2,3,4])
b = np.array([[2,3,4],[5,6,7]])
print((a-b)**2)
((a-b)**2).sum(axis=1)

[[0 0 0]
 [9 9 9]]


array([ 0, 27])

In [11]:
np.minimum(10, 10)

10

In [18]:
harris = np.array([10, 20, 30, 40, 50])
inds = [0, 1, 2]
harris[inds].argmax()

2

In [17]:
harris.shape

(5,)

In [24]:
is_active = [True, False, True]
print(np.where(is_active))
np.where(is_active)[0]

(array([0, 2]),)


array([0, 2])

In [2]:
a = np.array([[2, 3, 4],
           [5, 6, 7]])
a.shape

(2, 3)

In [3]:
a.reshape(3,2)

array([[2, 3],
       [4, 5],
       [6, 7]])

In [4]:
a

array([[2, 3, 4],
       [5, 6, 7]])

In [5]:
a.reshape(-1, 1)

array([[2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [6]:
a.reshape(1, -1)

array([[2, 3, 4, 5, 6, 7]])

In [3]:
b = np.array([[2, 3, 4],
            [5, 6, 7]])
b.reshape(-1,1)

array([[2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [4]:
c = np.array([0, 1, 2])
np.dot(b.reshape(-1, 1), c.reshape(1, -1))

array([[ 0,  2,  4],
       [ 0,  3,  6],
       [ 0,  4,  8],
       [ 0,  5, 10],
       [ 0,  6, 12],
       [ 0,  7, 14]])

In [4]:
np.sum(b)

9

In [7]:
np.sum(b, 1)

array([ 9, 18])

In [15]:
x = np.array([ 
                [
                    [2, 3, 4],
                    [5, 6, 7] 
                ],
                [ 
                    [8, 9, 10],
                    [11, 12, 13] 
                ] ])
x[0, 1, 2]
x.shape

(2, 2, 3)

In [19]:
x[0, 1] = [200, 300, 400]
x

array([[[  2,   3,   4],
        [200, 300, 400]],

       [[  8,   9,  10],
        [ 11,  12,  13]]])

In [7]:
a = np.array([10, 100, 1000])

In [8]:
for i, j in enumerate(a):
    print(i, " ", j)

0   10
1   100
2   1000


In [2]:
a = np.array([1, 4, 5, 2, 10, 3])
b = np.argsort(a)
b

array([0, 3, 5, 1, 2, 4])

In [3]:
a

array([ 1,  4,  5,  2, 10,  3])

In [4]:
a < 5

array([ True,  True, False,  True, False,  True])

In [7]:
np.where(a<5)

(array([0, 1, 3, 5]),)

In [8]:
np.where(a<5)[0]

array([0, 1, 3, 5])

In [14]:
np.random.choice( 5, 4, replace=False)

array([1, 2, 4, 0])

In [27]:
coeff= np.array([False, False, False, 1])
coeff.any()

True

In [28]:
coeff= np.array([False, False, False, False])
coeff.any()

False

In [5]:
labels = np.array([3, 4, 5])
labels.max()


5