In [19]:
import numpy as np

In [10]:
a = np.array([2,3,4])
b = np.array([[2,3,4],[5,6,7]])
print((a-b)**2)
((a-b)**2).sum(axis=1)

[[0 0 0]
 [9 9 9]]


array([ 0, 27])

In [11]:
np.minimum(10, 10)

10

In [18]:
harris = np.array([10, 20, 30, 40, 50])
inds = [0, 1, 2]
harris[inds].argmax()

2

In [17]:
harris.shape

(5,)

In [24]:
is_active = [True, False, True]
print(np.where(is_active))
np.where(is_active)[0]

(array([0, 2]),)


array([0, 2])