In [1]:
import numpy as np

In [10]:
a = np.array([2,3,4])
b = np.array([[2,3,4],[5,6,7]])
print((a-b)**2)
((a-b)**2).sum(axis=1)

[[0 0 0]
 [9 9 9]]


array([ 0, 27])

In [11]:
np.minimum(10, 10)

10